export const Userdata = [
  {
    id: 1,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "Song",
    email: "system@localhost",
    phoneNumber: "123-456-7890",
    roles: [{ name: "ADMIN" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 2,
    activated: false,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phoneNumber: "987-654-3210",
    roles: [{ name: "USER" }],
    status: "Offline",
  },
  {
    id: 3,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 4,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 5,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 6,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 7,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 8,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 9,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 10,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
  {
    id: 11,
    activated: true,
    imageUrl: "https://cdn-icons-png.flaticon.com/512/5556/5556499.png",
    name: "John Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-555-5555",
    roles: [{ name: "USER" }, { name: "MANAGER" }],
    status: "Online",
  },
];

export const categories = [
  { id: 1, name: "Electronics" },
  { id: 2, name: "Books" },
  { id: 3, name: "Clothing" },
  { id: 4, name: "Home & Kitchen" },
  { id: 5, name: "Sports & Outdoors" },
  { id: 6, name: "Health & Beauty" },
  { id: 7, name: "Toys & Games" },
  { id: 8, name: "Automotive" },
  { id: 9, name: "Office Supplies" },
  { id: 10, name: "Pet Supplies" },
];

export const brands = [
  { id: 1, name: "Nike" },
  { id: 2, name: "Adidas" },
  { id: 3, name: "Apple" },
  { id: 4, name: "Samsung" },
  { id: 5, name: "Sony" },
  { id: 6, name: "Microsoft" },
  { id: 7, name: "Toyota" },
  { id: 8, name: "Honda" },
  { id: 9, name: "Coca-Cola" },
  { id: 10, name: "Pepsi" },
];
export const productData = [
  {
    id: 1,
    name: "Product 1",
    brand: "Brand 1",
    category: "Category 1",
    description: "Description 1",
    price: 100,
    stock_quantity: 10,
    sold_quantity: 2,
    imageUrls: [
      "https://via.placeholder.com/50",
      "https://via.placeholder.com/50",
    ],
  },
  {
    id: 2,
    name: "Product 2",
    brand: "Brand 2",
    category: "Category 2",
    description: "Description 2",
    price: 150,
    stock_quantity: 5,
    sold_quantity: 1,
    imageUrls: [
      "https://via.placeholder.com/50",
      "https://via.placeholder.com/50",
    ],
  },
  {
    id: 3,
    name: "Product 3",
    brand: "Brand 3",
    category: "Category 3",
    description: "Description 3",
    price: 200,
    stock_quantity: 8,
    sold_quantity: 3,
    imageUrls: [
      "https://via.placeholder.com/50",
      "https://via.placeholder.com/50",
    ],
  },
];

export const cartItems = [
  {
    id: 1,
    image:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/58e2c1a3-73df-4761-81e2-7cba45a5f183/initiator-shoes-jKr5LX.png",
    name: "Product 1",
    color: "Red",
    size: "M",
    price: 20000000,
    quantity: 1,
  },
  {
    id: 2,
    image:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/58e2c1a3-73df-4761-81e2-7cba45a5f183/initiator-shoes-jKr5LX.png",
    name: "Product 2",
    color: "Blue",
    size: "L",
    price: 1500000,
    quantity: 1,
  },
  {
    id: 3,
    image:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/58e2c1a3-73df-4761-81e2-7cba45a5f183/initiator-shoes-jKr5LX.png",
    name: "Product 3",
    color: "Green",
    size: "S",
    price: 2000000,
    quantity: 3,
  },
];
